### ISSUE TITLE
issue with runAsRoot config

### ISSUE THREAD

**Issue by ashokkumarrathore** [askhatri/livycluster#3]
I am testing Livy k8s on cluster with some policies configured where "runAsRoot" is not allowed. Is there anyway to override this behaviour? I don't see any configs in Livy to do this. 
Error:
admission webhook "validating-webhook.openpolicyagent.org" denied the request: OPA-SAM-0006-security-context │
│ : runAsRoot is not allowed

**Comment by askhatri** [comment]
Actually, I'm new to the "runAsRoot" policy, so I'm not quite sure about it. As I understand it, we can try using a Privileged Service Account if possible.

Create a new service account for Livy with the "privileged" attribute set to true. This will grant the service account the necessary permissions to run containers as root. Assign to Livy: Assign this privileged service account to Livy's deployment or statefulset.

**Comment by ashokkumarrathore** [comment]
Thank you for the prompt response. 
Figured out the fix, spark has this config "spark.kubernetes.driver.podTemplateFile" using which we can set pod template file and provide values including runAsNonRoot.
